Vagrant.configure("2") do |config|

  do_common_azure_stuff = Proc.new do |azure, override|

      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
  end

  config.vm.define "vagrantVM" do |cfg|
    cfg.vm.box = 'azure'

    cfg.ssh.private_key_path = '~/.ssh/id_rsa'

    cfg.vm.provider :azure do |azure, override|
      do_common_azure_stuff.call azure, override

      #PROVIDE A LOCATION FOR VM
      azure.location="westeurope"

      azure.resource_group_name="CCGroupEU"
      azure.vm_name="vagrantVM"

      azure.vm_image_urn="Canonical:UbuntuServer:16.04-LTS:latest"

    end

    cfg.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
    end

  end

  config.vm.define "vagrantVMDB" do |cfg|
    cfg.vm.box = 'azure'

    cfg.ssh.private_key_path = '~/.ssh/id_rsa'

    cfg.vm.provider :azure do |azure, override|
      do_common_azure_stuff.call azure, override

      #PROVIDE A LOCATION FOR VM
      azure.location="westeurope"

      azure.resource_group_name="CCGroupEU"
      azure.vm_name="vagrantVMDB"

      azure.vm_image_urn="Canonical:UbuntuServer:16.04-LTS:latest"

    end

    cfg.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
    end
  end
end

 
